"""
Static normalized seed data for Buildora's Historical Steel Estimator Dataset.
Converted from the approved Buildora_Historical_Steel_Data.xlsx workbook.
Material Scope: Reinforcement Steel / Rebar
Steel Grade: Grade 60 (Dataset-level convention)
Weight Unit: LBS
"""

HISTORICAL_PROJECTS = [
    {
        "project_key": "P001",
        "project_title": "160 S Union Ave",
        "building_type": "Residential",
        "location": "160 S Union Ave, Los Angeles, CA 90026",
        "total_covered_area_sqft": 43338.0,
        "building_footprint_sqft": 8083.0,
        "basement_count": 0,
        "above_ground_floors": 7,
        "structural_system": "Reinforced Concrete Frame",
        "foundation_type": "Grade Beam",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 148520.0,
        "total_rebar_with_wastage_lbs": 155946.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.43,
        "completion_year": None,
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "1-3",
        "data_quality": "VERIFIED",
        "notes": "Ground & 2nd Floor Type I-A, Upper Floors Type III-A. 91 units."
    },
    {
        "project_key": "P002",
        "project_title": "326 Robinson St",
        "building_type": "Residential",
        "location": "326 Robinson St, Los Angeles, CA",
        "total_covered_area_sqft": 24666.0,
        "building_footprint_sqft": 7212.0,
        "basement_count": 0,
        "above_ground_floors": 5,
        "structural_system": "Mixed",
        "foundation_type": "Pile Foundation",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 42100.0,
        "total_rebar_with_wastage_lbs": 44205.0,
        "overall_rebar_ratio_lbs_per_sqft": 1.71,
        "completion_year": None,
        "source_file": "PDF_1_Robinson.pdf",
        "source_pages": "4-12",
        "data_quality": "PARTIAL",
        "notes": "Piling caissons and grade beams included. 20 units."
    },
    {
        "project_key": "P003",
        "project_title": "New Unit # 1 & 2 TO S.F.D.",
        "building_type": "Residential",
        "location": "452 S La Verne Ave, East Los Angeles, CA 90022",
        "total_covered_area_sqft": 2498.0,
        "building_footprint_sqft": 1554.0,
        "basement_count": 0,
        "above_ground_floors": 2,
        "structural_system": None,
        "foundation_type": "Footing",
        "floor_system": None,
        "total_rebar_net_lbs": 8450.0,
        "total_rebar_with_wastage_lbs": 8873.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.38,
        "completion_year": 2023,
        "source_file": "PDF_1_LaVerne.pdf",
        "source_pages": "13-14",
        "data_quality": "PARTIAL",
        "notes": "2 ADU + Residential extension. 3 units."
    },
    {
        "project_key": "P004",
        "project_title": "48-Unit Mixed Use Apartment",
        "building_type": "Mixed Use",
        "location": "525 E Broadway, Long Beach, CA 90802",
        "total_covered_area_sqft": 56260.0,
        "building_footprint_sqft": 13495.0,
        "basement_count": 1,
        "above_ground_floors": 7,
        "structural_system": "Mixed",
        "foundation_type": "Footing",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 178940.0,
        "total_rebar_with_wastage_lbs": 187887.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.18,
        "completion_year": 2025,
        "source_file": "PDF_1_LongBeach.pdf",
        "source_pages": "15-20",
        "data_quality": "PARTIAL",
        "notes": "5-Story IIIA over 2-Story IA over 1-Level Subterranean Garage. 48 units."
    },
    {
        "project_key": "P005",
        "project_title": "700 Virgil",
        "building_type": "Mixed Use",
        "location": "700 N Virgil Ave, Los Angeles, CA 90029",
        "total_covered_area_sqft": 81353.0,
        "building_footprint_sqft": 17052.0,
        "basement_count": 2,
        "above_ground_floors": 7,
        "structural_system": "Reinforced Concrete Frame",
        "foundation_type": "Mat Foundation",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 285430.0,
        "total_rebar_with_wastage_lbs": 299702.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.51,
        "completion_year": 2022,
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "21-28",
        "data_quality": "VERIFIED",
        "notes": "Commercial 9,537 SF, Residential 35,502 SF, Parking 28,504 SF. 37 units."
    },
    {
        "project_key": "P006",
        "project_title": "110 S Normandie Residence",
        "building_type": "Residential",
        "location": "100-118 S. Normandie Avenue, Los Angeles, CA 90004",
        "total_covered_area_sqft": 81904.0,
        "building_footprint_sqft": 21447.0,
        "basement_count": 1,
        "above_ground_floors": 6,
        "structural_system": "Reinforced Concrete Frame",
        "foundation_type": "MIXED",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 295120.0,
        "total_rebar_with_wastage_lbs": 309876.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.60,
        "completion_year": 2025,
        "source_file": "110S_Normandie_Estimate_04_25_25.pdf",
        "source_pages": "1-28",
        "data_quality": "VERIFIED",
        "notes": "Type III-A & IA, 88 units. Extensive structural rebar takeoff."
    },
    {
        "project_key": "P007",
        "project_title": "Hudson house Addition and New Detached ADU & Garage",
        "building_type": "Residential",
        "location": "853 S Hudson Ave, Los Angeles, CA 90005",
        "total_covered_area_sqft": 7560.0,
        "building_footprint_sqft": 5163.0,
        "basement_count": 0,
        "above_ground_floors": 2,
        "structural_system": "Wood / Light Frame",
        "foundation_type": "Footing",
        "floor_system": "Wood Joist & Beam",
        "total_rebar_net_lbs": 14210.0,
        "total_rebar_with_wastage_lbs": 14921.0,
        "overall_rebar_ratio_lbs_per_sqft": 1.88,
        "completion_year": 2024,
        "source_file": "PDF_2_Hudson.pdf",
        "source_pages": "37-41",
        "data_quality": "PARTIAL",
        "notes": "2 ADU + 2 Cars Garage + 2 Floor Extension."
    },
    {
        "project_key": "P008",
        "project_title": "930 S Mansfield Ave",
        "building_type": "Residential",
        "location": "930 S Mansfield Ave, Los Angeles, CA 90036",
        "total_covered_area_sqft": 17856.0,
        "building_footprint_sqft": 8331.0,
        "basement_count": 1,
        "above_ground_floors": 4,
        "structural_system": "Mixed",
        "foundation_type": "Footing",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 58420.0,
        "total_rebar_with_wastage_lbs": 61341.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.27,
        "completion_year": 2025,
        "source_file": "PDF_2_Mansfield.pdf",
        "source_pages": "41-50",
        "data_quality": "VERIFIED",
        "notes": "Type I-A Basement & III-A Ground to 4th Floor. 19 units."
    },
    {
        "project_key": "P009",
        "project_title": "84TH Street Apartments",
        "building_type": "Residential",
        "location": "932 W 84TH Street, Los Angeles, CA 90044",
        "total_covered_area_sqft": 19414.0,
        "building_footprint_sqft": 4646.0,
        "basement_count": 0,
        "above_ground_floors": 4,
        "structural_system": "Wood / Light Frame",
        "foundation_type": "Footing",
        "floor_system": "Wood Joist & Beam",
        "total_rebar_net_lbs": 22150.0,
        "total_rebar_with_wastage_lbs": 23258.0,
        "overall_rebar_ratio_lbs_per_sqft": 1.14,
        "completion_year": 2024,
        "source_file": "PDF_2_84thStreet.pdf",
        "source_pages": "50-52",
        "data_quality": "PARTIAL",
        "notes": "Type V-A-FS, 36 units."
    },
    {
        "project_key": "P010",
        "project_title": "951 Chautauqua",
        "building_type": "Residential",
        "location": "951 Chautauqua Blvd, Pacific Palisades, CA 90272",
        "total_covered_area_sqft": 6495.0,
        "building_footprint_sqft": None,
        "basement_count": 1,
        "above_ground_floors": 2,
        "structural_system": "Wood / Light Frame",
        "foundation_type": "Grade Beam",
        "floor_system": None,
        "total_rebar_net_lbs": 18450.0,
        "total_rebar_with_wastage_lbs": 19373.0,
        "overall_rebar_ratio_lbs_per_sqft": 2.84,
        "completion_year": 2026,
        "source_file": "PDF_2_Chautauqua.pdf",
        "source_pages": "52-55",
        "data_quality": "PARTIAL",
        "notes": "Single Family Dwelling (SFD). Basement + 2 Floors. Type VB."
    },
    {
        "project_key": "P011",
        "project_title": "1334 Goucher St",
        "building_type": "Residential",
        "location": "1334 Goucher St, Pacific Palisades, CA 90272",
        "total_covered_area_sqft": 6850.0,
        "building_footprint_sqft": None,
        "basement_count": 1,
        "above_ground_floors": 2,
        "structural_system": "Wood / Light Frame",
        "foundation_type": "Grade Beam",
        "floor_system": None,
        "total_rebar_net_lbs": 21840.0,
        "total_rebar_with_wastage_lbs": 22932.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.19,
        "completion_year": 2026,
        "source_file": "PDF_3_Goucher.pdf",
        "source_pages": "1-5",
        "data_quality": "PARTIAL",
        "notes": "2 + Basement. Type V."
    },
    {
        "project_key": "P012",
        "project_title": "1351 N Stanley",
        "building_type": "Residential",
        "location": "1351 N Stanley Ave, Los Angeles, CA",
        "total_covered_area_sqft": 8767.0,
        "building_footprint_sqft": 6277.0,
        "basement_count": 0,
        "above_ground_floors": 3,
        "structural_system": None,
        "foundation_type": "Footing",
        "floor_system": None,
        "total_rebar_net_lbs": 16820.0,
        "total_rebar_with_wastage_lbs": 17661.0,
        "overall_rebar_ratio_lbs_per_sqft": 1.92,
        "completion_year": 2023,
        "source_file": "PDF_3_Stanley.pdf",
        "source_pages": "5-6",
        "data_quality": "PARTIAL",
        "notes": "4 units, 3 floors."
    },
    {
        "project_key": "P013",
        "project_title": "1925 Montrose Street",
        "building_type": "Residential",
        "location": "1925 Montrose St, Los Angeles, CA 90026",
        "total_covered_area_sqft": 26269.0,
        "building_footprint_sqft": 7862.0,
        "basement_count": 1,
        "above_ground_floors": 5,
        "structural_system": "Mixed",
        "foundation_type": "Footing",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 94180.0,
        "total_rebar_with_wastage_lbs": 98889.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.59,
        "completion_year": 2024,
        "source_file": "PDF_3_Montrose.pdf",
        "source_pages": "6-24",
        "data_quality": "VERIFIED",
        "notes": "5 Floors + Garage. 19 units."
    },
    {
        "project_key": "P014",
        "project_title": "2310W Ocean View",
        "building_type": "Residential",
        "location": "2310 W Ocean View Ave, Los Angeles, CA 90057",
        "total_covered_area_sqft": None,
        "building_footprint_sqft": 5565.0,
        "basement_count": 0,
        "above_ground_floors": 7,
        "structural_system": None,
        "foundation_type": "Footing",
        "floor_system": None,
        "total_rebar_net_lbs": 48620.0,
        "total_rebar_with_wastage_lbs": 51051.0,
        "overall_rebar_ratio_lbs_per_sqft": None,
        "completion_year": 2022,
        "source_file": "PDF_3_OceanView.pdf",
        "source_pages": "24-33",
        "data_quality": "PARTIAL",
        "notes": "24 units, 7 floors."
    },
    {
        "project_key": "P015",
        "project_title": "75 Unit Affordable ED-1 Housing Project",
        "building_type": "Residential",
        "location": "3455 W Slauson Ave, Los Angeles, CA 90043",
        "total_covered_area_sqft": 50222.0,
        "building_footprint_sqft": 50222.0,
        "basement_count": 1,
        "above_ground_floors": 5,
        "structural_system": "Mixed",
        "foundation_type": "Mat Foundation",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 164280.0,
        "total_rebar_with_wastage_lbs": 172494.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.27,
        "completion_year": 2024,
        "source_file": "PDF_4_Slauson.pdf",
        "source_pages": "13-24",
        "data_quality": "VERIFIED",
        "notes": "75 units, 1-Story Type I-A Parking + 5-Story Type III-A."
    },
    {
        "project_key": "P016",
        "project_title": "Ohio Street",
        "building_type": "Residential",
        "location": "4120 Ohio St, San Diego, CA 92104",
        "total_covered_area_sqft": None,
        "building_footprint_sqft": None,
        "basement_count": 0,
        "above_ground_floors": 7,
        "structural_system": "Mixed",
        "foundation_type": "Grade Beam",
        "floor_system": None,
        "total_rebar_net_lbs": 78450.0,
        "total_rebar_with_wastage_lbs": 82373.0,
        "overall_rebar_ratio_lbs_per_sqft": None,
        "completion_year": 2025,
        "source_file": "PDF_4_Ohio.pdf",
        "source_pages": "24-33",
        "data_quality": "PARTIAL",
        "notes": "IIIA 5 Stories over IA 2 Stories."
    },
    {
        "project_key": "P017",
        "project_title": "4212 Mclaughlin Ave",
        "building_type": "Residential",
        "location": "4212 McLaughlin Ave, Culver City, CA 90066",
        "total_covered_area_sqft": 3632.0,
        "building_footprint_sqft": 1886.0,
        "basement_count": 0,
        "above_ground_floors": 2,
        "structural_system": "Wood / Light Frame",
        "foundation_type": "Grade Beam",
        "floor_system": None,
        "total_rebar_net_lbs": 8940.0,
        "total_rebar_with_wastage_lbs": 9387.0,
        "overall_rebar_ratio_lbs_per_sqft": 2.46,
        "completion_year": 2026,
        "source_file": "PDF_4_McLaughlin.pdf",
        "source_pages": "41-44",
        "data_quality": "PARTIAL",
        "notes": "SFD, 2 floors. Type V-B."
    },
    {
        "project_key": "P018",
        "project_title": "108 Unit Multifamily Building",
        "building_type": "Residential",
        "location": "4311 W Sunset BLVD, Los Angeles, CA 90029",
        "total_covered_area_sqft": 101211.0,
        "building_footprint_sqft": None,
        "basement_count": 2,
        "above_ground_floors": 4,
        "structural_system": "Mixed",
        "foundation_type": "Mat Foundation",
        "floor_system": "Flat Slab",
        "total_rebar_net_lbs": 342150.0,
        "total_rebar_with_wastage_lbs": 359258.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.38,
        "completion_year": 2025,
        "source_file": "PDF_4_Sunset.pdf",
        "source_pages": "44-58",
        "data_quality": "VERIFIED",
        "notes": "108 units, Type IIIA 4 Stories over 2 Type IA Basements."
    },
    {
        "project_key": "P019",
        "project_title": "5318-Hoover Street Apartments",
        "building_type": "Residential",
        "location": "5310-16 Hoover St, Los Angeles, CA 90037",
        "total_covered_area_sqft": None,
        "building_footprint_sqft": None,
        "basement_count": None,
        "above_ground_floors": None,
        "structural_system": None,
        "foundation_type": "Footing",
        "floor_system": None,
        "total_rebar_net_lbs": 19480.0,
        "total_rebar_with_wastage_lbs": 20454.0,
        "overall_rebar_ratio_lbs_per_sqft": None,
        "completion_year": 2023,
        "source_file": "PDF_4_Hoover.pdf",
        "source_pages": "58-61",
        "data_quality": "PARTIAL",
        "notes": "Historical apartment building rebar takeoff."
    },
    {
        "project_key": "P020",
        "project_title": "4127 30th St",
        "building_type": "Residential",
        "location": "4127 30th St, San Diego, CA 92104",
        "total_covered_area_sqft": 38486.0,
        "building_footprint_sqft": None,
        "basement_count": 0,
        "above_ground_floors": 7,
        "structural_system": "Mixed",
        "foundation_type": "Grade Beam",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 128450.0,
        "total_rebar_with_wastage_lbs": 134873.0,
        "overall_rebar_ratio_lbs_per_sqft": 3.34,
        "completion_year": 2025,
        "source_file": "PDF_4_30thSt.pdf",
        "source_pages": "33-41",
        "data_quality": "VERIFIED",
        "notes": "48 units, IIIA 5 Stories over IA 2 Stories."
    },
    {
        "project_key": "P021",
        "project_title": "798 W Howard",
        "building_type": "Residential",
        "location": "798 W Howard Street, Marina Del Rey, CA 90292",
        "total_covered_area_sqft": 730.0,
        "building_footprint_sqft": None,
        "basement_count": 1,
        "above_ground_floors": 1,
        "structural_system": None,
        "foundation_type": "Footing",
        "floor_system": None,
        "total_rebar_net_lbs": 4210.0,
        "total_rebar_with_wastage_lbs": 4421.0,
        "overall_rebar_ratio_lbs_per_sqft": 5.77,
        "completion_year": 2024,
        "source_file": "PDF_3_Howard.pdf",
        "source_pages": "33-37",
        "data_quality": "PARTIAL",
        "notes": "1 floor + basement."
    },
    {
        "project_key": "P022",
        "project_title": "Austin Commercial Tower B",
        "building_type": "Commercial",
        "location": "Austin, TX",
        "total_covered_area_sqft": 45000.0,
        "building_footprint_sqft": None,
        "basement_count": 0,
        "above_ground_floors": 6,
        "structural_system": "Reinforced Concrete Frame",
        "foundation_type": "Spread Footing",
        "floor_system": "Beam & Slab",
        "total_rebar_net_lbs": 225000.0,
        "total_rebar_with_wastage_lbs": 236250.0,
        "overall_rebar_ratio_lbs_per_sqft": 5.00,
        "completion_year": 2024,
        "source_file": "Buildora_Seed_Active_Projects",
        "source_pages": "N/A",
        "data_quality": "REFERENCE",
        "notes": "REFERENCE / LEGACY_BUILDORA_REFERENCE record for Grade 60 baseline."
    }
]

HISTORICAL_LEVELS = [
    {
        "level_key": "P001_L01",
        "project_key": "P001",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Footings & Grade Beams",
        "area_sqft": None,
        "rebar_net_lbs": 18420.0,
        "rebar_with_wastage_lbs": 19341.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "1",
        "data_quality": "VERIFIED",
        "notes": "Footing & grade beam rebar; partial level elements."
    },
    {
        "level_key": "P001_L02",
        "project_key": "P001",
        "level_type": "GROUND",
        "level_number": 0,
        "level_label": "Ground Floor Slab & Walls",
        "area_sqft": 8083.0,
        "rebar_net_lbs": 31250.0,
        "rebar_with_wastage_lbs": 32813.0,
        "rebar_ratio_lbs_per_sqft": 3.87,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "1-2",
        "data_quality": "VERIFIED",
        "notes": "Ground floor concrete deck & wall rebar."
    },
    {
        "level_key": "P001_L03",
        "project_key": "P001",
        "level_type": "UPPER_FLOOR",
        "level_number": 2,
        "level_label": "Concrete Deck 2nd Floor",
        "area_sqft": 8083.0,
        "rebar_net_lbs": 12648.0,
        "rebar_with_wastage_lbs": 13280.0,
        "rebar_ratio_lbs_per_sqft": 1.56,
        "quantity_scope": "SECTION_ONLY",
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "2",
        "data_quality": "VERIFIED",
        "notes": "2nd floor concrete slab section."
    },
    {
        "level_key": "P001_L04",
        "project_key": "P001",
        "level_type": "UPPER_FLOOR",
        "level_number": 3,
        "level_label": "Concrete Deck 3rd Floor",
        "area_sqft": 8083.0,
        "rebar_net_lbs": 27009.0,
        "rebar_with_wastage_lbs": 28359.0,
        "rebar_ratio_lbs_per_sqft": 3.34,
        "quantity_scope": "SECTION_ONLY",
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "2",
        "data_quality": "VERIFIED",
        "notes": "3rd floor concrete slab section."
    },
    {
        "level_key": "P001_L05",
        "project_key": "P001",
        "level_type": "UPPER_FLOOR",
        "level_number": 4,
        "level_label": "Concrete Deck 4th Floor",
        "area_sqft": 8083.0,
        "rebar_net_lbs": 3307.0,
        "rebar_with_wastage_lbs": 3472.0,
        "rebar_ratio_lbs_per_sqft": 0.41,
        "quantity_scope": "SECTION_ONLY",
        "source_file": "PDF_1_Union_Ave.pdf",
        "source_pages": "2",
        "data_quality": "VERIFIED",
        "notes": "4th floor concrete slab section."
    },
    {
        "level_key": "P005_L01",
        "project_key": "P005",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Mat Footing F3 & Pad Footings",
        "area_sqft": None,
        "rebar_net_lbs": 50385.0,
        "rebar_with_wastage_lbs": 52905.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "21-23",
        "data_quality": "VERIFIED",
        "notes": "Mat Footing F3 & Pad Footings full rebar."
    },
    {
        "level_key": "P005_L02",
        "project_key": "P005",
        "level_type": "BASEMENT",
        "level_number": 2,
        "level_label": "Mat Slab @ P2",
        "area_sqft": 11500.0,
        "rebar_net_lbs": 47932.0,
        "rebar_with_wastage_lbs": 50329.0,
        "rebar_ratio_lbs_per_sqft": 4.17,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "24-25",
        "data_quality": "VERIFIED",
        "notes": "P2 Basement Mat Slab."
    },
    {
        "level_key": "P005_L03",
        "project_key": "P005",
        "level_type": "BASEMENT",
        "level_number": 1,
        "level_label": "Concrete Slab @ P1",
        "area_sqft": 12632.0,
        "rebar_net_lbs": 39587.0,
        "rebar_with_wastage_lbs": 41566.0,
        "rebar_ratio_lbs_per_sqft": 3.13,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "31",
        "data_quality": "VERIFIED",
        "notes": "P1 Basement Slab."
    },
    {
        "level_key": "P005_L04",
        "project_key": "P005",
        "level_type": "GROUND",
        "level_number": 0,
        "level_label": "Concrete Slab @ 1st Floor",
        "area_sqft": 11672.0,
        "rebar_net_lbs": 41939.0,
        "rebar_with_wastage_lbs": 44036.0,
        "rebar_ratio_lbs_per_sqft": 3.59,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "36",
        "data_quality": "VERIFIED",
        "notes": "1st Floor Slab."
    },
    {
        "level_key": "P005_L05",
        "project_key": "P005",
        "level_type": "UPPER_FLOOR",
        "level_number": 2,
        "level_label": "Concrete Slab @ 2nd Floor",
        "area_sqft": 14455.0,
        "rebar_net_lbs": 60248.0,
        "rebar_with_wastage_lbs": 63261.0,
        "rebar_ratio_lbs_per_sqft": 4.17,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_1_Virgil.pdf",
        "source_pages": "42",
        "data_quality": "VERIFIED",
        "notes": "2nd Floor Slab."
    },
    {
        "level_key": "P006_L01",
        "project_key": "P006",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Grade Beams, Footings, Pad Footings",
        "area_sqft": None,
        "rebar_net_lbs": 88734.0,
        "rebar_with_wastage_lbs": 93175.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "110S_Normandie_Estimate_04_25_25.pdf",
        "source_pages": "6-7",
        "data_quality": "VERIFIED",
        "notes": "Grade Beams GB-1, GB-2 & Pad Footings F8, F9."
    },
    {
        "level_key": "P006_L02",
        "project_key": "P006",
        "level_type": "GROUND",
        "level_number": 0,
        "level_label": "1st Floor Concrete Slab",
        "area_sqft": 22105.0,
        "rebar_net_lbs": 25199.0,
        "rebar_with_wastage_lbs": 26459.0,
        "rebar_ratio_lbs_per_sqft": 1.14,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "110S_Normandie_Estimate_04_25_25.pdf",
        "source_pages": "8",
        "data_quality": "VERIFIED",
        "notes": "1st Floor Elevated Concrete Slab."
    },
    {
        "level_key": "P006_L03",
        "project_key": "P006",
        "level_type": "UPPER_FLOOR",
        "level_number": 2,
        "level_label": "2nd Floor Concrete Slab",
        "area_sqft": 17570.0,
        "rebar_net_lbs": 25419.0,
        "rebar_with_wastage_lbs": 26690.0,
        "rebar_ratio_lbs_per_sqft": 1.45,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "110S_Normandie_Estimate_04_25_25.pdf",
        "source_pages": "8",
        "data_quality": "VERIFIED",
        "notes": "Combines 15\" (13,341 lbs) and 16.5\" (12,078 lbs) 2nd floor slabs."
    },
    {
        "level_key": "P008_L01",
        "project_key": "P008",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Footings & Pad Footings",
        "area_sqft": None,
        "rebar_net_lbs": 14500.0,
        "rebar_with_wastage_lbs": 15225.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_2_Mansfield.pdf",
        "source_pages": "42-43",
        "data_quality": "VERIFIED",
        "notes": "Footings & Pad Footings."
    },
    {
        "level_key": "P008_L02",
        "project_key": "P008",
        "level_type": "BASEMENT",
        "level_number": 1,
        "level_label": "Basement Slab & Stem Walls",
        "area_sqft": 5653.0,
        "rebar_net_lbs": 19452.0,
        "rebar_with_wastage_lbs": 20424.0,
        "rebar_ratio_lbs_per_sqft": 3.44,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_2_Mansfield.pdf",
        "source_pages": "44-46",
        "data_quality": "VERIFIED",
        "notes": "Basement Slab & Stem Walls."
    },
    {
        "level_key": "P008_L03",
        "project_key": "P008",
        "level_type": "GROUND",
        "level_number": 0,
        "level_label": "1st Floor Slab & Beams",
        "area_sqft": 4500.0,
        "rebar_net_lbs": 14850.0,
        "rebar_with_wastage_lbs": 15593.0,
        "rebar_ratio_lbs_per_sqft": 3.30,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_2_Mansfield.pdf",
        "source_pages": "48-49",
        "data_quality": "VERIFIED",
        "notes": "1st Floor Slab & Beams."
    },
    {
        "level_key": "P013_L01",
        "project_key": "P013",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Footings & Caissons",
        "area_sqft": None,
        "rebar_net_lbs": 18500.0,
        "rebar_with_wastage_lbs": 19425.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_3_Montrose.pdf",
        "source_pages": "6-10",
        "data_quality": "VERIFIED",
        "notes": "Footings & Caissons."
    },
    {
        "level_key": "P013_L02",
        "project_key": "P013",
        "level_type": "BASEMENT",
        "level_number": 1,
        "level_label": "Garage/Basement Slab",
        "area_sqft": 7862.0,
        "rebar_net_lbs": 28999.0,
        "rebar_with_wastage_lbs": 30449.0,
        "rebar_ratio_lbs_per_sqft": 3.69,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_3_Montrose.pdf",
        "source_pages": "18",
        "data_quality": "VERIFIED",
        "notes": "Garage/Basement Slab."
    },
    {
        "level_key": "P013_L03",
        "project_key": "P013",
        "level_type": "GROUND",
        "level_number": 0,
        "level_label": "1st Floor Concrete Slab",
        "area_sqft": 7240.0,
        "rebar_net_lbs": 28999.0,
        "rebar_with_wastage_lbs": 30449.0,
        "rebar_ratio_lbs_per_sqft": 4.01,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_3_Montrose.pdf",
        "source_pages": "18",
        "data_quality": "VERIFIED",
        "notes": "1st Floor Concrete Slab."
    },
    {
        "level_key": "P015_L01",
        "project_key": "P015",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Footings & Mat Footing",
        "area_sqft": None,
        "rebar_net_lbs": 38400.0,
        "rebar_with_wastage_lbs": 40320.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_4_Slauson.pdf",
        "source_pages": "14-16",
        "data_quality": "VERIFIED",
        "notes": "Footings & Mat Footing."
    },
    {
        "level_key": "P015_L02",
        "project_key": "P015",
        "level_type": "BASEMENT",
        "level_number": 1,
        "level_label": "1st Floor / Parking Deck (P1)",
        "area_sqft": 50222.0,
        "rebar_net_lbs": 69128.0,
        "rebar_with_wastage_lbs": 72584.0,
        "rebar_ratio_lbs_per_sqft": 1.38,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_4_Slauson.pdf",
        "source_pages": "22",
        "data_quality": "VERIFIED",
        "notes": "1st Floor / Parking Deck (P1)."
    },
    {
        "level_key": "P018_L01",
        "project_key": "P018",
        "level_type": "FOUNDATION",
        "level_number": None,
        "level_label": "Footings & Pier Caps",
        "area_sqft": None,
        "rebar_net_lbs": 48200.0,
        "rebar_with_wastage_lbs": 50610.0,
        "rebar_ratio_lbs_per_sqft": None,
        "quantity_scope": "PARTIAL_LEVEL",
        "source_file": "PDF_4_Sunset.pdf",
        "source_pages": "45-47",
        "data_quality": "VERIFIED",
        "notes": "Footings & Pier Caps."
    },
    {
        "level_key": "P018_L02",
        "project_key": "P018",
        "level_type": "BASEMENT",
        "level_number": 2,
        "level_label": "Concrete Deck @ P2",
        "area_sqft": 20000.0,
        "rebar_net_lbs": 51927.0,
        "rebar_with_wastage_lbs": 54524.0,
        "rebar_ratio_lbs_per_sqft": 2.60,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_4_Sunset.pdf",
        "source_pages": "55",
        "data_quality": "VERIFIED",
        "notes": "Concrete Deck @ P2."
    },
    {
        "level_key": "P018_L03",
        "project_key": "P018",
        "level_type": "BASEMENT",
        "level_number": 1,
        "level_label": "Concrete Deck @ P1",
        "area_sqft": 20000.0,
        "rebar_net_lbs": 69128.0,
        "rebar_with_wastage_lbs": 72584.0,
        "rebar_ratio_lbs_per_sqft": 3.46,
        "quantity_scope": "COMPLETE_LEVEL",
        "source_file": "PDF_4_Sunset.pdf",
        "source_pages": "55",
        "data_quality": "VERIFIED",
        "notes": "Concrete Deck @ P1."
    }
]

HISTORICAL_COMPONENTS = [
    {"component_key": "P001_C01", "project_key": "P001", "level_key": "P001_L01", "component_type": "FOOTING", "component_label": "3' X 24'' Concrete Footing", "rebar_net_lbs": 2395.0, "rebar_with_wastage_lbs": 2516.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "1", "data_quality": "VERIFIED", "notes": "#7 & #5 rebar"},
    {"component_key": "P001_C02", "project_key": "P001", "level_key": "P001_L01", "component_type": "ELEVATOR_PIT", "component_label": "24\" Concrete Elevator Pit", "rebar_net_lbs": 500.0, "rebar_with_wastage_lbs": 524.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#7 & #5 rebar"},
    {"component_key": "P001_C03", "project_key": "P001", "level_key": "P001_L02", "component_type": "SLAB_ON_GRADE", "component_label": "4\" Thk Slab on Grade", "rebar_net_lbs": 8126.0, "rebar_with_wastage_lbs": 8533.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#4 @ 16\" O.C."},
    {"component_key": "P001_C04", "project_key": "P001", "level_key": "P001_L03", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Deck (2nd Floor)", "rebar_net_lbs": 12648.0, "rebar_with_wastage_lbs": 13280.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#5 @ 12\" O.C."},
    {"component_key": "P001_C05", "project_key": "P001", "level_key": "P001_L04", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Slab (3rd Floor)", "rebar_net_lbs": 27009.0, "rebar_with_wastage_lbs": 28359.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#5 @ 12\" O.C."},
    {"component_key": "P001_C06", "project_key": "P001", "level_key": "P001_L05", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Deck (4th Floor)", "rebar_net_lbs": 3307.0, "rebar_with_wastage_lbs": 3472.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#5 @ 12\" O.C."},
    {"component_key": "P001_C07", "project_key": "P001", "level_key": None, "component_type": "WALL", "component_label": "8\" Concrete Wall (10'6\"H)", "rebar_net_lbs": 15372.0, "rebar_with_wastage_lbs": 16142.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "2", "data_quality": "VERIFIED", "notes": "#5 & #7 rebar"},
    {"component_key": "P001_C08", "project_key": "P001", "level_key": None, "component_type": "SHOTCRETE_WALL", "component_label": "8\" Shotcrete Wall", "rebar_net_lbs": 8794.0, "rebar_with_wastage_lbs": 9234.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "3", "data_quality": "VERIFIED", "notes": "#5 & #6 rebar"},
    {"component_key": "P001_C09", "project_key": "P001", "level_key": None, "component_type": "STAIR", "component_label": "Concrete Stair 1 & 2", "rebar_net_lbs": 1111.0, "rebar_with_wastage_lbs": 1167.0, "source_file": "PDF_1_Union_Ave.pdf", "source_pages": "3", "data_quality": "VERIFIED", "notes": "#7, #5 & #4 nosing"},
    {"component_key": "P002_C01", "project_key": "P002", "level_key": None, "component_type": "PILE", "component_label": "Concrete Piling P1-P9", "rebar_net_lbs": 11200.0, "rebar_with_wastage_lbs": 11760.0, "source_file": "PDF_1_Robinson.pdf", "source_pages": "4-5", "data_quality": "VERIFIED", "notes": "(10) #9 rebar & #4 ties"},
    {"component_key": "P002_C02", "project_key": "P002", "level_key": None, "component_type": "GRADE_BEAM", "component_label": "Concrete Grade Beams", "rebar_net_lbs": 6150.0, "rebar_with_wastage_lbs": 6458.0, "source_file": "PDF_1_Robinson.pdf", "source_pages": "5-6", "data_quality": "VERIFIED", "notes": "#7, #6 & #4 ties"},
    {"component_key": "P002_C03", "project_key": "P002", "level_key": None, "component_type": "FOOTING", "component_label": "Concrete Footing 5'x30\"", "rebar_net_lbs": 6320.0, "rebar_with_wastage_lbs": 6636.0, "source_file": "PDF_1_Robinson.pdf", "source_pages": "6-7", "data_quality": "VERIFIED", "notes": "#7, #6 & #5 dowels"},
    {"component_key": "P005_C01", "project_key": "P005", "level_key": "P005_L01", "component_type": "MAT_FOOTING", "component_label": "4' W x 30\" Thk Mat Footing (540 LF)", "rebar_net_lbs": 26508.0, "rebar_with_wastage_lbs": 27833.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "21", "data_quality": "VERIFIED", "notes": "#7 & #5 dowels"},
    {"component_key": "P005_C02", "project_key": "P005", "level_key": "P005_L01", "component_type": "MAT_FOOTING", "component_label": "5' W x 30\" Thk Mat Footing F3", "rebar_net_lbs": 6918.0, "rebar_with_wastage_lbs": 7264.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "22", "data_quality": "VERIFIED", "notes": "#7 & #6 dowels"},
    {"component_key": "P005_C03", "project_key": "P005", "level_key": "P005_L01", "component_type": "PAD_FOOTING", "component_label": "13' x 13' x 42\" Concrete Pad Footing (8EA)", "rebar_net_lbs": 16959.0, "rebar_with_wastage_lbs": 17808.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "23", "data_quality": "VERIFIED", "notes": "#8 & dowels"},
    {"component_key": "P005_C04", "project_key": "P005", "level_key": "P005_L02", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Mat Slab @ P2", "rebar_net_lbs": 47932.0, "rebar_with_wastage_lbs": 50329.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "24-25", "data_quality": "VERIFIED", "notes": "#5 @ 12\" O.C."},
    {"component_key": "P005_C05", "project_key": "P005", "level_key": "P005_L03", "component_type": "ELEVATED_SLAB", "component_label": "9\" Thk Concrete Slab @ P1", "rebar_net_lbs": 39587.0, "rebar_with_wastage_lbs": 41566.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "31", "data_quality": "VERIFIED", "notes": "#5 @ 16\" O.C."},
    {"component_key": "P005_C06", "project_key": "P005", "level_key": "P005_L04", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Slab @ 1st Floor", "rebar_net_lbs": 41939.0, "rebar_with_wastage_lbs": 44036.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "36", "data_quality": "VERIFIED", "notes": "#5 @ 14\" O.C."},
    {"component_key": "P005_C07", "project_key": "P005", "level_key": "P005_L05", "component_type": "ELEVATED_SLAB", "component_label": "14\" Thk Concrete Slab @ 2nd Floor", "rebar_net_lbs": 60248.0, "rebar_with_wastage_lbs": 63261.0, "source_file": "PDF_1_Virgil.pdf", "source_pages": "42", "data_quality": "VERIFIED", "notes": "#5 @ 12\" O.C."},
    {"component_key": "P006_C01", "project_key": "P006", "level_key": "P006_L01", "component_type": "GRADE_BEAM", "component_label": "13' Wide x 48\" Thk Grade Beam GB-1", "rebar_net_lbs": 20130.0, "rebar_with_wastage_lbs": 21138.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "6", "data_quality": "VERIFIED", "notes": "#8, #9 & #4 ties"},
    {"component_key": "P006_C02", "project_key": "P006", "level_key": "P006_L01", "component_type": "GRADE_BEAM", "component_label": "48\" Thk Grade Beam GB-2", "rebar_net_lbs": 42784.0, "rebar_with_wastage_lbs": 44926.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "6", "data_quality": "VERIFIED", "notes": "#8, #9, #6 & #7 dowels"},
    {"component_key": "P006_C03", "project_key": "P006", "level_key": "P006_L01", "component_type": "PAD_FOOTING", "component_label": "Continuous Footings F-a, F-b, F-c & Pad F8, F9", "rebar_net_lbs": 25820.0, "rebar_with_wastage_lbs": 27111.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "6-7", "data_quality": "VERIFIED", "notes": "#5, #6, #7, #8 & #9 rebar"},
    {"component_key": "P006_C04", "project_key": "P006", "level_key": None, "component_type": "SLAB_ON_GRADE", "component_label": "5\" Thk Slab on Grade", "rebar_net_lbs": 19103.0, "rebar_with_wastage_lbs": 20058.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "7", "data_quality": "VERIFIED", "notes": "#4 @ 18\" O.C."},
    {"component_key": "P006_C05", "project_key": "P006", "level_key": "P006_L02", "component_type": "ELEVATED_SLAB", "component_label": "12.5\" Thk Concrete Slab @ 1st Floor", "rebar_net_lbs": 25199.0, "rebar_with_wastage_lbs": 26459.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "8", "data_quality": "VERIFIED", "notes": "#4 & #5 rebar"},
    {"component_key": "P006_C06", "project_key": "P006", "level_key": "P006_L03", "component_type": "ELEVATED_SLAB", "component_label": "15\" & 16.5\" Thk Concrete Slab @ 2nd Floor", "rebar_net_lbs": 25419.0, "rebar_with_wastage_lbs": 26690.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "8", "data_quality": "VERIFIED", "notes": "#4 & #6 rebar"},
    {"component_key": "P006_C07", "project_key": "P006", "level_key": None, "component_type": "COLUMN", "component_label": "Concrete Columns C1, C2, C3", "rebar_net_lbs": 26710.0, "rebar_with_wastage_lbs": 28046.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "7-8", "data_quality": "VERIFIED", "notes": "#6, #7, #9 & #4 ties"},
    {"component_key": "P006_C08", "project_key": "P006", "level_key": None, "component_type": "RETAINING_WALL", "component_label": "Shotcrete & Shear Walls W1-W4, SW", "rebar_net_lbs": 68530.0, "rebar_with_wastage_lbs": 71957.0, "source_file": "110S_Normandie_Estimate_04_25_25.pdf", "source_pages": "7-8", "data_quality": "VERIFIED", "notes": "#5, #6, #7 dowels & rebar"},
    {"component_key": "P008_C01", "project_key": "P008", "level_key": "P008_L01", "component_type": "FOOTING", "component_label": "3'x24\" & 4'x24\" Concrete Footings", "rebar_net_lbs": 5100.0, "rebar_with_wastage_lbs": 5355.0, "source_file": "PDF_2_Mansfield.pdf", "source_pages": "42", "data_quality": "VERIFIED", "notes": "#6 rebar"},
    {"component_key": "P008_C02", "project_key": "P008", "level_key": "P008_L01", "component_type": "PAD_FOOTING", "component_label": "8'x8'x24\" & 11'x11'x28\" Pad Footings", "rebar_net_lbs": 3222.0, "rebar_with_wastage_lbs": 3383.0, "source_file": "PDF_2_Mansfield.pdf", "source_pages": "43", "data_quality": "VERIFIED", "notes": "#8 & #9 rebar"},
    {"component_key": "P008_C03", "project_key": "P008", "level_key": "P008_L02", "component_type": "SLAB_ON_GRADE", "component_label": "5\" Thk Slab on Grade", "rebar_net_lbs": 7552.0, "rebar_with_wastage_lbs": 7929.0, "source_file": "PDF_2_Mansfield.pdf", "source_pages": "44", "data_quality": "VERIFIED", "notes": "#4 @ 12\" O.C."},
    {"component_key": "P008_C04", "project_key": "P008", "level_key": "P008_L02", "component_type": "WALL", "component_label": "12\" Thk Concrete Walls", "rebar_net_lbs": 11900.0, "rebar_with_wastage_lbs": 12495.0, "source_file": "PDF_2_Mansfield.pdf", "source_pages": "45-46", "data_quality": "VERIFIED", "notes": "#5, #6, #7 dowels"},
    {"component_key": "P013_C01", "project_key": "P013", "level_key": "P013_L01", "component_type": "FOOTING", "component_label": "Concrete Footings & Pad Footing", "rebar_net_lbs": 12500.0, "rebar_with_wastage_lbs": 13125.0, "source_file": "PDF_3_Montrose.pdf", "source_pages": "7-10", "data_quality": "VERIFIED", "notes": "#5, #6, #8, #9 dowels"},
    {"component_key": "P013_C02", "project_key": "P013", "level_key": "P013_L02", "component_type": "SLAB_ON_GRADE", "component_label": "4\" Thk Slab on Grade", "rebar_net_lbs": 6568.0, "rebar_with_wastage_lbs": 6897.0, "source_file": "PDF_3_Montrose.pdf", "source_pages": "10", "data_quality": "VERIFIED", "notes": "#4 @ 16\" O.C."},
    {"component_key": "P013_C03", "project_key": "P013", "level_key": "P013_L03", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Slab @ 1st Floor", "rebar_net_lbs": 28999.0, "rebar_with_wastage_lbs": 30449.0, "source_file": "PDF_3_Montrose.pdf", "source_pages": "18", "data_quality": "VERIFIED", "notes": "#6 @ 18\" O.C."},
    {"component_key": "P013_C04", "project_key": "P013", "level_key": None, "component_type": "COLUMN", "component_label": "Concrete Columns C1-C11", "rebar_net_lbs": 11840.0, "rebar_with_wastage_lbs": 12432.0, "source_file": "PDF_3_Montrose.pdf", "source_pages": "11-13", "data_quality": "VERIFIED", "notes": "#9, #10 & #4 ties"},
    {"component_key": "P013_C05", "project_key": "P013", "level_key": None, "component_type": "SHOTCRETE_WALL", "component_label": "10\" & 12\" Shotcrete Walls", "rebar_net_lbs": 34273.0, "rebar_with_wastage_lbs": 35987.0, "source_file": "PDF_3_Montrose.pdf", "source_pages": "13-16", "data_quality": "VERIFIED", "notes": "#5 & #6 rebar"},
    {"component_key": "P015_C01", "project_key": "P015", "level_key": "P015_L01", "component_type": "FOOTING", "component_label": "12\" & 24\" Wide Concrete Footings", "rebar_net_lbs": 3210.0, "rebar_with_wastage_lbs": 3371.0, "source_file": "PDF_4_Slauson.pdf", "source_pages": "14-15", "data_quality": "VERIFIED", "notes": "#4, #5 dowels"},
    {"component_key": "P015_C02", "project_key": "P015", "level_key": "P015_L01", "component_type": "MAT_FOOTING", "component_label": "24\" Thk Concrete Mat Slab (5347 SF)", "rebar_net_lbs": 20023.0, "rebar_with_wastage_lbs": 21024.0, "source_file": "PDF_4_Slauson.pdf", "source_pages": "16", "data_quality": "VERIFIED", "notes": "#6 @ 12\" O.C."},
    {"component_key": "P015_C03", "project_key": "P015", "level_key": None, "component_type": "SLAB_ON_GRADE", "component_label": "5\" Thk Slab on Grade", "rebar_net_lbs": 11231.0, "rebar_with_wastage_lbs": 11793.0, "source_file": "PDF_4_Slauson.pdf", "source_pages": "16", "data_quality": "VERIFIED", "notes": "#4 @ 16\" O.C."},
    {"component_key": "P015_C04", "project_key": "P015", "level_key": "P015_L02", "component_type": "ELEVATED_SLAB", "component_label": "14\" & 16\" Thk Concrete Deck @ P1", "rebar_net_lbs": 69128.0, "rebar_with_wastage_lbs": 72584.0, "source_file": "PDF_4_Slauson.pdf", "source_pages": "22", "data_quality": "VERIFIED", "notes": "#5, #6, #7, #8, #9 rebar"},
    {"component_key": "P018_C01", "project_key": "P018", "level_key": "P018_L01", "component_type": "FOOTING", "component_label": "2'8\", 3'8\", 3'10\" Concrete Footings", "rebar_net_lbs": 11434.0, "rebar_with_wastage_lbs": 12006.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "45-47", "data_quality": "VERIFIED", "notes": "#4 & #5 dowels"},
    {"component_key": "P018_C02", "project_key": "P018", "level_key": "P018_L01", "component_type": "PAD_FOOTING", "component_label": "5'x5', 7'x7', 8'x8', 9'x9', 10'x10' Pad Footings", "rebar_net_lbs": 23150.0, "rebar_with_wastage_lbs": 24308.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "48-49", "data_quality": "VERIFIED", "notes": "#6, #7, #8 dowels"},
    {"component_key": "P018_C03", "project_key": "P018", "level_key": None, "component_type": "SLAB_ON_GRADE", "component_label": "5\" Thk Slab on Grade", "rebar_net_lbs": 32088.0, "rebar_with_wastage_lbs": 33693.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "49", "data_quality": "VERIFIED", "notes": "#4 @ 16\" O.C."},
    {"component_key": "P018_C04", "project_key": "P018", "level_key": "P018_L02", "component_type": "ELEVATED_SLAB", "component_label": "12\" Thk Concrete Deck @ P2", "rebar_net_lbs": 51927.0, "rebar_with_wastage_lbs": 54524.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "55", "data_quality": "VERIFIED", "notes": "#5, #6, #7, #8, #9 rebar"},
    {"component_key": "P018_C05", "project_key": "P018", "level_key": "P018_L03", "component_type": "ELEVATED_SLAB", "component_label": "14\" & 16\" Thk Concrete Deck @ P1", "rebar_net_lbs": 69128.0, "rebar_with_wastage_lbs": 72584.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "55", "data_quality": "VERIFIED", "notes": "#5, #6, #7, #8, #9 rebar"},
    {"component_key": "P018_C06", "project_key": "P018", "level_key": None, "component_type": "SHOTCRETE_WALL", "component_label": "10\" Shotcrete Walls (P3)", "rebar_net_lbs": 48950.0, "rebar_with_wastage_lbs": 51398.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "49-51", "data_quality": "VERIFIED", "notes": "#4 & #5 rebar"},
    {"component_key": "P018_C07", "project_key": "P018", "level_key": None, "component_type": "COLUMN", "component_label": "Concrete Columns C1, C2, C3, C4", "rebar_net_lbs": 26415.0, "rebar_with_wastage_lbs": 27736.0, "source_file": "PDF_4_Sunset.pdf", "source_pages": "52-54", "data_quality": "VERIFIED", "notes": "#8, #9, #10 & #4 ties"},
    {"component_key": "P020_C01", "project_key": "P020", "level_key": None, "component_type": "GRADE_BEAM", "component_label": "5'x2'6\", 2'x2' Grade Beams", "rebar_net_lbs": 8010.0, "rebar_with_wastage_lbs": 8411.0, "source_file": "PDF_4_30thSt.pdf", "source_pages": "34", "data_quality": "VERIFIED", "notes": "#5, #6, #8 & #4 stirrups"},
    {"component_key": "P020_C02", "project_key": "P020", "level_key": None, "component_type": "PIER", "component_label": "5' & 2'6\" Thk Concrete Pier Caps", "rebar_net_lbs": 19280.0, "rebar_with_wastage_lbs": 20244.0, "source_file": "PDF_4_30thSt.pdf", "source_pages": "34-35", "data_quality": "VERIFIED", "notes": "#6, #8, #9 rebar"},
    {"component_key": "P020_C03", "project_key": "P020", "level_key": None, "component_type": "SLAB_ON_GRADE", "component_label": "8\" Thk Concrete Slab on Grade", "rebar_net_lbs": 19300.0, "rebar_with_wastage_lbs": 20265.0, "source_file": "PDF_4_30thSt.pdf", "source_pages": "36", "data_quality": "VERIFIED", "notes": "#6 @ 12\" O.C."},
    {"component_key": "P020_C04", "project_key": "P020", "level_key": None, "component_type": "WALL", "component_label": "12\", 8\", 16\" Concrete Shear Walls", "rebar_net_lbs": 37610.0, "rebar_with_wastage_lbs": 39491.0, "source_file": "PDF_4_30thSt.pdf", "source_pages": "37-38", "data_quality": "VERIFIED", "notes": "#5, #6, #8 rebar"},
    {"component_key": "P022_C01", "project_key": "P022", "level_key": None, "component_type": "ISOLATED_FOOTING", "component_label": "Spread Footings Grade 60", "rebar_net_lbs": 45000.0, "rebar_with_wastage_lbs": 47250.0, "source_file": "Buildora_Seed_Active_Projects", "source_pages": "N/A", "data_quality": "REFERENCE", "notes": "Grade 60 steel."},
    {"component_key": "P022_C02", "project_key": "P022", "level_key": None, "component_type": "COLUMN", "component_label": "Concrete Columns C1-C6", "rebar_net_lbs": 65000.0, "rebar_with_wastage_lbs": 68250.0, "source_file": "Buildora_Seed_Active_Projects", "source_pages": "N/A", "data_quality": "REFERENCE", "notes": "Grade 60 steel."},
    {"component_key": "P022_C03", "project_key": "P022", "level_key": None, "component_type": "ELEVATED_SLAB", "component_label": "Beam & Slab Floor System", "rebar_net_lbs": 115000.0, "rebar_with_wastage_lbs": 120750.0, "source_file": "Buildora_Seed_Active_Projects", "source_pages": "N/A", "data_quality": "REFERENCE", "notes": "Grade 60 steel."}
]
